public enum ExperienceModeType
{
	Pilgrim,
	Voyageur,
	Stalker,
	Story,
	ChallengeRescue,
	ChallengeHunted,
	ChallengeWhiteout,
	ChallengeNomad,
	ChallengeHuntedPart2,
	Interloper,
	Custom,
	StoryFresh,
	StoryHardened,
	FourDaysOfNight,
	ChallengeArchivist,
	ChallengeDeadManWalking,
	EventWintersEmbrace,
	ChallengeNowhereToHide,
	NUM_MODES
}
