namespace Users;

public enum XboxOnePrivileges
{
	XPRIVILEGE_ADD_FRIEND = 255,
	XPRIVILEGE_BROADCAST = 190,
	XPRIVILEGE_CLOUD_GAMING_JOIN_SESSION = 208,
	XPRIVILEGE_CLOUD_GAMING_MANAGE_SESSION = 207,
	XPRIVILEGE_CLOUD_SAVED_GAMES = 209,
	XPRIVILEGE_COMMUNICATIONS = 252,
	XPRIVILEGE_COMMUNICATION_VOICE_INGAME = 205,
	XPRIVILEGE_COMMUNICATION_VOICE_SKYPE = 206,
	XPRIVILEGE_FREE_CONTENT = 193,
	XPRIVILEGE_GAME_DVR = 198,
	XPRIVILEGE_MULTIPLAYER_PARTIES = 203,
	XPRIVILEGE_MULTIPLAYER_SESSIONS = 254,
	XPRIVILEGE_NOUPSELL = 215,
	XPRIVILEGE_PREMIUM_CONTENT = 214,
	XPRIVILEGE_PREMIUM_VIDEO = 224,
	XPRIVILEGE_PROFILE_VIEWING = 249,
	XPRIVILEGE_PURCHASE_CONTENT = 245,
	XPRIVILEGE_SHARE_CONTENT = 211,
	XPRIVILEGE_SHARE_KINECT_CONTENT = 199,
	XPRIVILEGE_SOCIAL_NETWORK_SHARING = 220,
	XPRIVILEGE_SUBSCRIPTION_CONTENT = 219,
	XPRIVILEGE_USER_CREATED_CONTENT = 247,
	XPRIVILEGE_VIDEO_COMMUNICATIONS = 235,
	XPRIVILEGE_VIEW_FRIENDS_LIST = 197,
	XPRIVILEGE_INTERNET_BROWSING = 217,
	XPRIVILEGE_SESSIONS = 189,
	XPRIVILEGE_FITNESS_UPLOAD = 195
}
