namespace Storage;

public enum ConnectedStorageStatus
{
	WAITING_FOR_RESULT,
	FAILED_BUSY,
	FAILED_UNINITIAISSED,
	FAILED_NOUSERSET,
	FAILED_CONNECTEDSTORAGESPACE,
	FAILED_BLOBNOTFOUND,
	FAILED_INVALIDCONTAINERNAME,
	FAILED_NOACCESS,
	FAILED_NOXBOXLIVEINFO,
	FAILED_OUTOFLOCALSTORAGE,
	FAILED_PROVIDEDBUFFERTOOSMALL,
	FAILED_QUOTAEXCEEDED,
	FAILED_UPDATETOOBIG,
	FAILED_USERCANCELED,
	FAILED_CANCELED,
	FAILED_ERROR,
	FAILED_UNKNOWN,
	SUCCESS
}
